import { useState } from "react";
import { Link } from "react-router-dom";
import axios from "../../utils/api";
import { motion } from "framer-motion";
import { ArrowRight, Building2, UserRound, Truck } from "lucide-react";

const Register=()=>{
 const [form,setForm]=useState({name:"",email:"",password:"",role:"customer",note:"",organization:"",gstin:"",vendorItems:[{name:"",description:""}]});
 const [loading,setLoading]=useState(false); const [success,setSuccess]=useState(false);
 const set=(k,v)=>setForm({...form,[k]:v});
 const handleItem=(i,k,v)=>setForm({...form,vendorItems:form.vendorItems.map((x,n)=>n===i?{...x,[k]:v}:x)});
 const handleSubmit=async(e)=>{e.preventDefault();setLoading(true);try{const payload={...form};if(form.role!=="vendor"){delete payload.organization;delete payload.gstin;delete payload.vendorItems;}await axios.post("/auth/register",payload);setSuccess(true);}catch(err){alert(err.response?.data?.message||"Registration failed. Try again.");}finally{setLoading(false);}};
 if(success)return <div className="min-h-screen bg-[#07111f] flex items-center justify-center p-6 text-center text-white"><div><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-3xl bg-cyan-300 text-3xl text-slate-950">✓</div><h2 className="mt-6 text-3xl font-black">Registration submitted</h2><p className="mt-2 text-slate-400">Please wait for the cooperative to approve your account.</p><Link to="/login" className="mt-7 inline-flex rounded-2xl bg-cyan-300 px-6 py-3 font-black text-slate-950">Back to login</Link></div></div>;
 return <div className="relative min-h-[calc(100vh-64px)] overflow-hidden bg-[#07111f] py-10 text-white"><div className="absolute right-[-8rem] top-[-8rem] h-[30rem] w-[30rem] rounded-full bg-blue-500/15 blur-3xl"/><div className="relative mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-[.8fr_1.2fr] lg:items-center">
 <section className="hidden lg:block"><p className="text-sm font-black uppercase tracking-[.18em] text-cyan-300">Join ProcureHub</p><h1 className="mt-3 text-5xl font-black leading-tight">One platform. <span className="text-cyan-300">Three perspectives.</span></h1><p className="mt-5 max-w-md leading-7 text-slate-400">Register according to your role and enter a workspace designed around the procurement work you actually do.</p><div className="mt-8 space-y-3">{[[UserRound,"Customer","Create and track procurement requests."],[Truck,"Vendor","Respond to opportunities and manage quotes."],[Building2,"Cooperative","Coordinate the complete workflow."]].map(([Icon,title,desc])=><div key={title} className="flex gap-4 rounded-2xl border border-white/10 bg-white/[.04] p-4"><Icon className="text-cyan-300"/><div><p className="font-bold">{title}</p><p className="text-sm text-slate-500">{desc}</p></div></div>)}</div></section>
 <motion.section initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="rounded-[2rem] border border-white/10 bg-white/[.07] p-6 shadow-2xl backdrop-blur-xl sm:p-9"><p className="text-sm font-bold text-cyan-300">Create account</p><h2 className="mt-2 text-3xl font-black">Set up your workspace.</h2><form onSubmit={handleSubmit} className="mt-7 space-y-5">
 <div className="grid gap-5 sm:grid-cols-2"><label><span className="text-sm font-bold text-slate-200">Full name</span><input required value={form.name} onChange={e=>set("name",e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-400"/></label><label><span className="text-sm font-bold text-slate-200">Email</span><input type="email" required value={form.email} onChange={e=>set("email",e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-400"/></label></div>
 <label><span className="text-sm font-bold text-slate-200">Password</span><input type="password" minLength={6} required value={form.password} onChange={e=>set("password",e.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-400"/></label>
 <div><span className="text-sm font-bold text-slate-200">I am registering as</span><div className="mt-2 grid gap-3 sm:grid-cols-2">{["customer","vendor"].map(role=><button type="button" key={role} onClick={()=>set("role",role)} className={`rounded-2xl border p-4 text-left transition ${form.role===role?"border-cyan-300 bg-cyan-300/10":"border-white/10 bg-black/10"}`}><p className="font-black capitalize">{role}</p><p className="mt-1 text-xs text-slate-500">{role==="vendor"?"Supply products and submit quotations":"Raise and manage procurement requests"}</p></button>)}</div></div>
 {form.role==="vendor"&&<div className="space-y-4 rounded-2xl border border-white/10 bg-black/10 p-4"><div className="grid gap-4 sm:grid-cols-2"><input required placeholder="Organization name" value={form.organization} onChange={e=>set("organization",e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none focus:border-cyan-400"/><input required placeholder="GSTIN" value={form.gstin} onChange={e=>set("gstin",e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none focus:border-cyan-400"/></div>{form.vendorItems.map((item,i)=><div key={i} className="grid gap-3 sm:grid-cols-2"><input placeholder="Item name" value={item.name} onChange={e=>handleItem(i,"name",e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none"/><input placeholder="Description" value={item.description} onChange={e=>handleItem(i,"description",e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none"/></div>)}<button type="button" onClick={()=>setForm({...form,vendorItems:[...form.vendorItems,{name:"",description:""}]})} className="text-sm font-bold text-cyan-300">+ Add another item</button></div>}
 <textarea placeholder="Note for admin (optional)" rows={3} value={form.note} onChange={e=>set("note",e.target.value)} className="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-400"/>
 <button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-300 py-3.5 font-black text-slate-950 hover:bg-cyan-200 disabled:opacity-60">{loading?"Submitting...":<>Submit registration <ArrowRight size={17}/></>}</button>
 <p className="text-center text-sm text-slate-400">Already registered? <Link to="/login" className="font-black text-cyan-300">Login</Link></p></form></motion.section></div></div>;
};
export default Register;